name: PyTest

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry config virtualenvs.create true

    - name: Install dependencies
      run: poetry install --no-root

    - name: Activate virtual environment
      run: poetry shell

    - name: Run PyTest
      run: poetry run pytest
